# Generated by Django 2.2.1 on 2019-09-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pubish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.Publish')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
