# Generated by Django 2.2.1 on 2019-09-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubish',
            new_name='publish',
        ),
    ]
