# Generated by Django 2.2.1 on 2019-09-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20190912_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_person',
            new_name='person',
        ),
    ]
