# Generated by Django 2.2.1 on 2019-09-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20190912_1112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
